config:
  install_path_scheme: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"
  source_cache:
    - ~/.spack_downloads
  misc_cache:
    - $spack/var/spack/cache
  build_jobs: 16
