packages:
  ascent:
    variants: ~fortran~openmp+python
  boost:
    version: [1.76.0]
    variants: cxxstd=14
  conduit:
    variants: ~fortran~hdf5_compat
  catalyst:
    variants: +osmesa~python+python3+essentials+extras+rendering
  emacs:
    variants: +tls
  fftw:
    variants: +fma
  gcc:
    variants: languages=c,c++,fortran,go
  hdf5:
    version: [1.12.2]
    variants: +cxx+hl
  hypre:
    version: [2.26.0]
    variants: +int64~superlu-dist~fortran
  intel-parallel-studio:
    variants: +advisor+inspector+itac+mkl+vtune
  llvm:
    variants: +omp_debug+omp_tsan+python build_type=Release
  nalu-wind:
    variants: +openfast+tioga+hypre+fftw build_type=Release
  netcdf-c:
    version: [4.7.4]
    variants: +parallel-netcdf maxdims=65536 maxvars=524288
  openfast:
    version: [develop]
    variants: +cxx build_type=Release
  paraview:
    variants: +hdf5+python3~python+osmesa build_type=Release
  py-yt:
    variants: ~astropy
  parallel-netcdf:
    version: [1.12.2]
    variants: ~fortran
  sensei:
    variants: +catalyst+hdf5+python build_type=Release
  texlive:
    variants: scheme=full
  tioga:
    version: [develop]
  trilinos:
    version: [stable, develop]
    variants: ~adios2~alloptpkgs~amesos+amesos2~anasazi~aztec+belos+boost~chaco~complex~debug~dtk~epetra~epetraext+exodus+explicit_template_instantiation~float~fortran~fortrilinos+glm+gtest+hdf5~hypre~ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos~mesquite+metis~minitensor~ml+mpi+muelu~mumps~nox~openmp~phalanx~piro~python~rol~rythmos~sacado+shards~shylu+stk~stratimikos~suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra+uvm~x11~xsdkflags+zlib+zoltan+zoltan2 gotype=long cxxstd=14 build_type=Release
  visit:
    variants: ~gui+hdf5+python+silo+adios2
  vim:
    variants: +python+huge+cscope
  all:
    compiler: [gcc, intel, clang]
    variants: build_type=Release +mpi
    providers:
      mpi: [mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
