packages:
  cuda:
    buildable: false
    version: [11.4.4]
    externals:
    - spec: cuda@11.4.4
      prefix: /projects/hpacf/apps/compilers/2022-10/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/cuda-11.4.4-gzsu4bitcwa6ovuw5c32n2vgol3vbxbt
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=80 build_type=Release
  hwloc:
    variants: +cuda cuda_arch=80
  mpich:
    require: "@4.0.2"
    variants: +cuda cuda_arch=80
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=80 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=80 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  pgi:
    variants: +nvidia
  all:
    compiler: [gcc@10.4.0, clang@15.0.2]
    variants: build_type=Release +mpi
    target: [zen2]
    providers:
      mpi: [mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
